server:
  port: 8005

spring:
  application:
    name: demo-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: demo3-ribbon
    api-b:
      path: /api-b/**
      serviceId: demo-feign

