spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ylllw/spring-cloud-demo/
          searchPaths: config
          username:
          password:
      label: master


server:
  port: 8006


